Fixes problem with hard delete users.
Previously, we would get errors like this:
```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation)
update or delete on table "users" violates foreign key constraint
"fk_consultations_creator_id_users" on table "consultations"
DETAIL:  Key (id)=(ca258718-35bc-42a0-803d-13497fcb3639) is still referenced from table "consultations".
```
For this reason we needed to add 'SET NULL' to foreign key.
Also the key had to be created again in an upgrade task.